name: property_sales
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.1.0
  freezed: ^3.2.0
  flutter_bloc: ^9.1.1
  clock: ^1.1.2
  get_it: ^8.2.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  retrofit: ^4.7.1
  retrofit_generator: ^10.0.2
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  flutter_gen_runner: ^5.11.0

flutter_gen:
  output: lib/core/style/assets

flutter:
  uses-material-design: true

  assets:
    - assets/images/
